version: '3'
services:
    staffLocation:
        image: staff-location
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
        - 8080:8080
        volumes:
        - /home/coder/.ssh:/home/runner/.ssh/:ro
        restart: always
